import { Language } from '../types';

export const translations = {
  en: {
    // Navigation
    home: 'Home',
    search: 'Search',
    map: 'Map',
    recommendations: 'Recommendations',
    saved: 'Saved',
    profile: 'Profile',
    
    // Home
    searchPlaceholder: 'Search by city, town, or compound...',
    apartments: 'Apartments',
    villas: 'Villas',
    studios: 'Studios',
    cairo: 'Cairo',
    giza: 'Giza',
    recentListings: 'Recent Listings',
    createListing: 'Create Listing',
    getInstantPrice: 'Get Instant Estimate',
    listYourProperty: 'List Your Property',
    
    // Search & Filters
    filters: 'Filters',
    sort: 'Sort',
    city: 'City',
    town: 'Town',
    compound: 'Compound',
    priceRange: 'Price Range',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    propertyType: 'Property Type',
    furnished: 'Furnished',
    offering: 'Offering',
    sale: 'Sale',
    rent: 'Rent',
    newest: 'Newest',
    priceAsc: 'Price: Low to High',
    priceDesc: 'Price: High to Low',
    sizeAsc: 'Size: Small to Large',
    sizeDesc: 'Size: Large to Small',
    
    // Property Types
    apartment: 'Apartment',
    villa: 'Villa',
    studio: 'Studio',
    townhouse: 'Townhouse',
    penthouse: 'Penthouse',
    duplex: 'Duplex',
    chalet: 'Chalet',
    twin_house: 'Twin House',
    standalone_villa: 'Standalone Villa',
    
    // Listing Details
    verified: 'Verified',
    estimatePrice: 'Estimate Price',
    similarProperties: 'Similar Properties',
    share: 'Share',
    save: 'Save',
    contactSeller: 'Contact Seller',
    
    // Create Listing
    basics: 'Basics',
    location: 'Location',
    specifications: 'Specifications',
    pricing: 'Pricing',
    photos: 'Photos',
    completionStatus: 'Completion Status',
    ready: 'Ready',
    underConstruction: 'Under Construction',
    offPlan: 'Off Plan',
    size: 'Size (m²)',
    downPayment: 'Down Payment',
    askingPrice: 'Asking Price',
    uploadPhotos: 'Upload Photos',
    submit: 'Submit Listing',
    noPhoto: 'No Photo',
    
    // Profile
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    auto: 'Auto',
    about: 'About AqarHunt',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    
    // Profile page content
    welcomeToAqarHunt: 'Welcome to AqarHunt',
    realEstateCompanion: 'Your real estate companion for Egypt',
    settings: 'Settings',
    information: 'Information',
    
    // Common
    egp: 'EGP',
    br: 'BR',
    results: 'results',
    noResults: 'No properties found',
    loading: 'Loading...',
    error: 'Something went wrong',
    
    // About content
    aboutContent: `AqarHunt is a real-estate assistant for Egypt that helps buyers discover relevant properties and helps sellers estimate fair market prices. The app combines fast search and fuzzy matching with two core AI features: a <strong>Recommendation System</strong> that surfaces "more like this" homes, and a <strong>Price Prediction</strong> model that estimates value from location, type, size, rooms, and other attributes. It's designed for both buyers and sellers, with admin tooling planned next.

Under the hood, AqarHunt uses a content-based KNN recommender and a trained regression model to deliver ranked suggestions and instant price estimates—streamlining the search experience and supporting better, data-driven decisions for the Egyptian market.`,
    
    privacyContent: `We only use information needed to run recommendations and price estimates. That includes <strong>property listing data</strong> (e.g., city, town/compound, coordinates, property type, size, bedrooms/bathrooms, furnishing, completion status, offering type, and price) and <strong>basic preference inputs</strong> used to filter or personalize results. At this stage, AqarHunt is an ML-only backend developed in a notebook/server environment—no account profiles or sensitive personal identifiers are required to get recommendations or estimates.

Any data you submit to create a listing is stored for the purpose of producing an estimate and enabling similar-property recommendations. We aim to minimize what we collect, use it solely to power core features, and adapt the system for localization and quality improvements as the product matures.`,
    
    termsContent: `AqarHunt provides price estimates and recommendations for informational purposes only. Results are generated by machine-learning models trained on historical listings and may not reflect current market conditions; users should independently verify critical details before making decisions. The current release focuses on a backend ML system intended for integration into apps/APIs, and is offered "as is" while we continue to iterate and evaluate models.

By using AqarHunt, you agree not to misuse the service or the underlying data, and you acknowledge that AqarHunt is not liable for financial decisions made based on estimates or recommendations. As we expand features (e.g., accounts, saved searches), updated terms will clarify any additional responsibilities and rights.`,
    
    // Recommendations screen
    getAIPoweredRecommendations: 'Get AI-powered property recommendations',
    selectPropertyForRecommendations: 'Select a property to get recommendations',
    chooseProperty: 'Choose a property...',
    similarWithinFilters: 'Similar within Filters',
    similarPropertiesLive: 'Similar Properties (Live)',
    
    // Units
    squareMeters: 'm²',
    
    // Offering types
    saleOffering: 'Sale',
    rentOffering: 'Rent',
    
    // Cities in English
    cairoCity: 'Cairo',
    gizaCity: 'Giza',
    alexandriaCity: 'Alexandria',
    
    // Areas/Towns in English
    newCairo: 'New Cairo',
    heliopolis: 'Heliopolis',
    maadi: 'Maadi',
    zamalek: 'Zamalek',
    dokki: 'Dokki',
    mohandessin: 'Mohandessin',
    nasr_city: 'Nasr City',
    downtown: 'Downtown',
    agouza: 'Agouza',
    sixth_october: '6th of October',
    sheikh_zayed: 'Sheikh Zayed',
    
    // Saved Properties Actions
    remove: 'Remove',
    selectAll: 'Select All',
    
    // Map Tab
    propertiesFound: 'properties found',
    
    // Recommendations Tab
    describeYourProperty: 'Describe your property',
    useExistingListing: 'Use existing listing',
    similarWithinFilters: 'Similar within Filters',
    similarLive: 'Similar (Live)',
    fillPropertyDetailsForRecommendations: 'Fill in the property details above to get AI-powered recommendations',
    
    // Map popup
    viewFullDetails: 'View Full Details',
  },
  ar: {
    // Navigation
    home: 'الرئيسية',
    search: 'البحث',
    map: 'الخريطة',
    recommendations: 'التوصيات',
    saved: 'المحفوظات',
    profile: 'الملف الشخصي',
    
    // Home
    searchPlaceholder: 'ابحث بالمدينة أو المنطقة أو المجمع...',
    apartments: 'شقق',
    villas: 'فيلات',
    studios: 'استوديوهات',
    cairo: 'القاهرة',
    giza: 'الجيزة',
    recentListings: 'العقارات الحديثة',
    createListing: 'إنشاء إعلان',
    getInstantPrice: 'تقدير فوري للسعر',
    listYourProperty: 'أعلن عن عقارك',
    
    // Search & Filters
    filters: 'المرشحات',
    sort: 'ترتيب',
    city: 'المدينة',
    town: 'المنطقة',
    compound: 'المجمع',
    priceRange: 'نطاق السعر',
    bedrooms: 'غرف النوم',
    bathrooms: 'دورات المياه',
    propertyType: 'نوع العقار',
    furnished: 'مفروش',
    offering: 'نوع العرض',
    sale: 'بيع',
    rent: 'إيجار',
    newest: 'الأحدث',
    priceAsc: 'السعر: من الأقل للأعلى',
    priceDesc: 'السعر: من الأعلى للأقل',
    sizeAsc: 'المساحة: من الأصغر للأكبر',
    sizeDesc: 'المساحة: من الأكبر للأصغر',
    
    // Property Types
    apartment: 'شقة',
    villa: 'فيلا',
    studio: 'استوديو',
    townhouse: 'تاون هاوس',
    penthouse: 'بنتهاوس',
    duplex: 'دوبليكس',
    chalet: 'شاليه',
    twin_house: 'توين هاوس',
    standalone_villa: 'فيلا منفصلة',
    
    // Listing Details
    verified: 'موثق',
    estimatePrice: 'تقدير السعر',
    similarProperties: 'عقارات مشابهة',
    share: 'مشاركة',
    save: 'حفظ',
    contactSeller: 'تواصل مع البائع',
    
    // Create Listing
    basics: 'المعلومات الأساسية',
    location: 'الموقع',
    specifications: 'المواصفات',
    pricing: 'التسعير',
    photos: 'الصور',
    completionStatus: 'حالة الإنجاز',
    ready: 'جاهز',
    underConstruction: 'تحت الإنشاء',
    offPlan: 'على الخريطة',
    size: 'المساحة (م²)',
    downPayment: 'المقدم',
    askingPrice: 'السعر المطلوب',
    uploadPhotos: 'رفع الصور',
    submit: 'إرسال الإعلان',
    noPhoto: 'لا توجد صورة',
    
    // Additional Property Terms
    floor: 'الطابق',
    balcony: 'شرفة',
    garden: 'حديقة',
    parking: 'موقف سيارات',
    elevator: 'مصعد',
    security: 'أمن',
    gym: 'صالة رياضية',
    pool: 'حمام سباحة',
    view: 'إطلالة',
    seaView: 'إطلالة بحرية',
    cityView: 'إطلالة على المدينة',
    gardenView: 'إطلالة على الحديقة',
    
    // Property Features
    airConditioning: 'تكييف',
    centralHeating: 'تدفئة مركزية',
    builtInKitchen: 'مطبخ مجهز',
    builtInWardrobe: 'دولاب مدمج',
    ceramic: 'سيراميك',
    parquet: 'باركيه',
    marble: 'رخام',
    
    // Location Terms
    nearMetro: 'قريب من المترو',
    nearSchools: 'قريب من المدارس',
    nearHospitals: 'قريب من المستشفيات',
    nearMalls: 'قريب من المولات',
    nearMosque: 'قريب من المسجد',
    
    // Financial Terms
    totalPrice: 'السعر الإجمالي',
    pricePerMeter: 'سعر المتر',
    monthlyRent: 'الإيجار الشهري',
    yearlyRent: 'الإيجار السنوي',
    deposit: 'التأمين',
    commission: 'العمولة',
    maintenance: 'الصيانة',
    utilities: 'المرافق',
    
    // Status Terms
    available: 'متاح',
    sold: 'تم البيع',
    rented: 'تم التأجير',
    reserved: 'محجوز',
    underOffer: 'تحت العرض',
    
    // Contact Terms
    callNow: 'اتصل الآن',
    whatsapp: 'واتساب',
    email: 'بريد إلكتروني',
    viewPhone: 'عرض الهاتف',
    contactAgent: 'تواصل مع الوسيط',
    
    // Time Terms
    today: 'اليوم',
    yesterday: 'أمس',
    daysAgo: 'منذ {count} أيام',
    weeksAgo: 'منذ {count} أسابيع',
    monthsAgo: 'منذ {count} أشهر',
    
    // Action Terms
    viewDetails: 'عرض التفاصيل',
    viewPhotos: 'عرض الصور',
    viewMap: 'عرض الخريطة',
    compare: 'مقارنة',
    report: 'إبلاغ',
    favorite: 'مفضلة',
    unfavorite: 'إزالة من المفضلة',
    
    // Profile
    language: 'اللغة',
    theme: 'المظهر',
    light: 'فاتح',
    dark: 'داكن',
    auto: 'تلقائي',
    about: 'حول عقار هنت',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',
    
    // Profile page content
    welcomeToAqarHunt: 'مرحباً بك في عقار هنت',
    realEstateCompanion: 'رفيقك العقاري في مصر',
    settings: 'الإعدادات',
    information: 'المعلومات',
    
    // Common
    egp: 'ج.م',
    br: 'غرفة',
    results: 'نتيجة',
    noResults: 'لم يتم العثور على عقارات',
    loading: 'جاري التحميل...',
    error: 'حدث خطأ ما',
    
    // About content (Arabic translations)
    aboutContent: `عقار هنت هو مساعد عقاري لمصر يساعد المشترين في اكتشاف العقارات ذات الصلة ويساعد البائعين في تقدير أسعار السوق العادلة. يجمع التطبيق بين البحث السريع والمطابقة الضبابية مع ميزتين أساسيتين للذكاء الاصطناعي: <strong>نظام التوصيات</strong> الذي يعرض المنازل "المشابهة لهذا" و<strong>نموذج التنبؤ بالأسعار</strong> الذي يقدر القيمة من الموقع والنوع والحجم والغرف والسمات الأخرى. تم تصميمه للمشترين والبائعين، مع التخطيط لأدوات الإدارة التالية.

تحت الغطاء، يستخدم عقار هنت موصي KNN قائم على المحتوى ونموذج انحدار مدرب لتقديم اقتراحات مرتبة وتقديرات أسعار فورية - مما يبسط تجربة البحث ويدعم قرارات أفضل مدفوعة بالبيانات للسوق المصري.`,
    
    privacyContent: `\نحن نستخدم فقط المعلومات اللازمة لتشغيل التوصيات وتقديرات الأسعار. يشمل ذلك <strong>بيانات قوائم العقارات</strong> (مثل المدينة والبلدة/المجمع والإحداثيات ونوع العقار والحجم وغرف النوم/الحمامات والأثاث وحالة الإنجاز ونوع العرض والسعر) و<strong>مدخلات التفضيل الأساسية</strong> المستخدمة لتصفية أو تخصيص النتائج. في هذه المرحلة، عقار هنت هو خلفية ML فقط تم تطويرها في بيئة دفتر/خادم - لا توجد ملفات تعريف حساب أو معرفات شخصية حساسة مطلوبة للحصول على توصيات أو تقديرات.

أي بيانات تقدمها لإنشاء قائمة يتم تخزينها لغرض إنتاج تقدير وتمكين توصيات العقارات المماثلة. نهدف إلى تقليل ما نجمعه، واستخدامه فقط لتشغيل الميزات الأساسية، وتكييف النظام للتوطين وتحسينات الجودة مع نضج المنتج.`,
    
    termsContent: `يوفر عقار هنت تقديرات الأسعار والتوصيات لأغراض إعلامية فقط. يتم إنتاج النتائج بواسطة نماذج التعلم الآلي المدربة على القوائم التاريخية وقد لا تعكس ظروف السوق الحالية؛ يجب على المستخدمين التحقق بشكل مستقل من التفاصيل الحرجة قبل اتخاذ القرارات. تركز النسخة الحالية على نظام ML خلفي مخصص للتكامل في التطبيقات/واجهات برمجة التطبيقات، ويتم تقديمه "كما هو" بينما نواصل التكرار وتقييم النماذج.

باستخدام عقار هنت، فإنك توافق على عدم إساءة استخدام الخدمة أو البيانات الأساسية، وتقر بأن عقار هنت غير مسؤول عن القرارات المالية المتخذة بناءً على التقديرات أو التوصيات. مع توسيع الميزات (مثل الحسابات والبحث المحفوظ)، ستوضح الشروط المحدثة أي مسؤوليات وحقوق إضافية.`,
    
    // Recommendations screen
    getAIPoweredRecommendations: 'احصل على توصيات عقارية مدعومة بالذكاء الاصطناعي',
    selectPropertyForRecommendations: 'اختر عقاراً للحصول على التوصيات',
    chooseProperty: 'اختر عقاراً...',
    similarWithinFilters: 'مشابه ضمن المرشحات',
    similarPropertiesLive: 'عقارات مشابهة (مباشر)',
    
    // Units
    squareMeters: 'م²',
    
    // Offering types
    saleOffering: 'بيع',
    rentOffering: 'إيجار',
    
    // Cities in Arabic
    cairoCity: 'القاهرة',
    gizaCity: 'الجيزة',
    alexandriaCity: 'الإسكندرية',
    
    // Areas/Towns in Arabic
    newCairo: 'القاهرة الجديدة',
    heliopolis: 'مصر الجديدة',
    maadi: 'المعادي',
    zamalek: 'الزمالك',
    dokki: 'الدقي',
    mohandessin: 'المهندسين',
    nasr_city: 'مدينة نصر',
    downtown: 'وسط البلد',
    agouza: 'العجوزة',
    sixth_october: 'مدينة السادس من أكتوبر',
    sheikh_zayed: 'الشيخ زايد',
    
    // Saved Properties Actions
    remove: 'حذف',
    selectAll: 'تحديد الكل',
    
    // Map Tab
    propertiesFound: 'عقار تم العثور عليه',
    
    // Recommendations Tab
    describeYourProperty: 'وصف العقار الخاص بك',
    useExistingListing: 'استخدام إعلان موجود',
    similarWithinFilters: 'مشابه ضمن المرشحات',
    similarLive: 'مشابه (مباشر)',
    fillPropertyDetailsForRecommendations: 'املأ تفاصيل العقار أعلاه للحصول على توصيات مدعومة بالذكاء الاصطناعي',
    
    // Map popup
    viewFullDetails: 'عرض التفاصيل الكاملة',
  }
};

export function t(key: string, language: Language): string {
  return translations[language][key as keyof typeof translations.en] || key;
}